![](imgs/89.png)
![](imgs/90.png)
![](imgs/91.png)

# External Methods

![](imgs/92.png)
![](imgs/93.png)
![](imgs/94.png)

![](imgs/96.png)

In [3]:
# maximum matching
(40+30+30)/200

0.5

In [4]:
(50+40+20)/200

0.55

In [6]:
(50+20+40)/200

0.55

![](imgs/97.png)

![](imgs/98.png)

In [1]:
# pureza dos clusters https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-clustering-1.html#:~:text=Bad%20clusterings%20have%20purity%20values,this%20chapter%20in%20Table%2016.2%20.&text=High%20purity%20is%20easy%20to,document%20gets%20its%20own%20cluster.
(40+30+50)/200

0.6

In [17]:
from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.metrics import jaccard_score
import numpy as np

c1 = [int(item.strip().split()[1]) for item in open("data/clustering_1.txt", "r").readlines()]
c2 = [int(item.strip().split()[1]) for item in open("data/clustering_2.txt", "r").readlines()]
c3 = [int(item.strip().split()[1]) for item in open("data/clustering_3.txt", "r").readlines()]
c4 = [int(item.strip().split()[1]) for item in open("data/clustering_4.txt", "r").readlines()]
c5 = [int(item.strip().split()[1]) for item in open("data/clustering_5.txt", "r").readlines()]
t = [int(item.strip().split()[1]) for item in open("data/partitions.txt", "r").readlines()]

In [18]:
np.array(c1)

array([2, 0, 2, 1, 2, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 1, 0,
       0, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2,
       0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 0, 0, 0, 1, 0,
       0, 1, 2, 0, 2, 1, 1, 2, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 1, 2, 1, 2,
       1, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0,
       1, 1, 1, 2, 2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 2,
       2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 0, 1, 0, 0, 2, 0, 1, 2, 0, 0, 1, 1,
       0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 0, 1,
       0, 2, 1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 2, 1, 2,
       2, 2, 0, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2,
       2, 1, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2])

In [22]:
np.array(t)

array([2, 0, 2, 1, 2, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0,
       0, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2,
       0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 0, 0, 0, 1, 0,
       0, 1, 2, 0, 2, 1, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2,
       1, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0,
       1, 0, 1, 2, 2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 2,
       2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 2, 0, 1, 2, 0, 0, 1, 1,
       0, 0, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 0, 1,
       0, 2, 1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 2, 1, 2,
       2, 2, 0, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2,
       2, 1, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2])

In [27]:
y_true = np.array([[0, 1, 1],
...                    [1, 1, 0]])
y_true[0]

array([0, 1, 1])

In [36]:
NMI = []
JSCORE = []
for c in [c1, c2, c3, c4, c5]:
    nmi_score = normalized_mutual_info_score(t, c, average_method="arithmetic")
    j_score = jaccard_score(np.array(t), np.array(c), average="micro")
    NMI.append(nmi_score)
    JSCORE.append(j_score)

In [39]:
NMI

[0.8896247665800587,
 0.6456368113477217,
 0.391543746381692,
 0.764277135869685,
 0.7336804366512119]

In [40]:
JSCORE

[0.9543973941368078,
 0.8126888217522659,
 0.6438356164383562,
 0.8348623853211009,
 0.5]

In [41]:
f = open("data/scores.txt", "w")
for nmi, j in zip(NMI, JSCORE):
    f.write("%s %s\n"%(nmi, j))
f.close()

![](imgs/99.png)

![](imgs/100.png)

![](imgs/101.png)

![](imgs/102.png)

![](imgs/103.png)

![](imgs/104.png)

![](imgs/105.png)

![](imgs/106.png)

![](imgs/107.png)